import Head from 'next/head'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

    function PostList( {posts} ){
        return (
            <>
            
            <Head>
                <title>Profile Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
            </Head>
            <Header />
            <h1>This is post list Page</h1>
            {
                        posts.map(
                            (post) => {
                                return (
                                    <div key={post.id}>
                                        <h2>{post.id}{post.title}</h2>
                                    </div>
                                )
                            }
                        )
            }
            
            <Footer />
            </>
        )
    }

    export default PostList

    export async function getStaticProps(){
        const response = await fetch('https://jsonplaceholder.typicode.com/posts')
        const data = await response.json()
        
        
        return{
            props: {
                posts: data.slice(0,3)
            }
        }

    }